[[config.projects]]
name = "🌹 roseate (WIP)"
description = "A fast, GPU-accelerated image viewer built for simplicity and customization."
link = "https://github.com/cloudy-org/roseate"
image = "https://raw.githubusercontent.com/cloudy-org/roseate/main/assets/alpha_preview_1.png"

[[config.projects]]
name = "🎞️ mov-cli"
description = "A cli tool that allows you to watch everything and anything from your terminal."
link = "https://github.com/mov-cli/mov-cli"
image = "./images/mov_cli_showcase.png"

[[config.projects]]
name = "✨🔥 fastapi-tailwind"
description = "Streamlined approach for adding TailwindCSS to FastAPI without NodeJS."
link = "https://github.com/THEGOLDENPRO/fastapi-tailwind"
image = "https://github.com/THEGOLDENPRO/fastapi-tailwind/raw/main/assets/example_page_showcase.png"

[[config.projects]]
name = "📚 AGHPB API"
description = "API that spits out anime girls holding programming books."
link = "https://github.com/THEGOLDENPRO/aghpb_api"
image = "https://github.com/THEGOLDENPRO/aghpb_api/raw/main/assets/screenshot_1.png"

[[config.projects]]
name = "🤍 Bad Apple in Ursina 🖤"
description = "Bad apple in a python 3d game engine, Ursina ʕ •ᴥ•ʔ."
link = "https://github.com/THEGOLDENPRO/Bad-Apple-in-Ursina"
image = "https://github.com/THEGOLDENPRO/Bad-Apple-in-Ursina/raw/master/images/preview.gif"

[[config.projects]]
name = "💛 Goldy Bot Framework"
description = "My custom tuned discord bot framework."
link = "https://github.com/Goldy-Bot/Goldy-Bot-Framework"
image = "https://github.com/Goldy-Bot/mal_cord/raw/main/assets/showcase_2.gif"

[[config.projects]]
name = "🐍 snakelings"
description = "A collection of small exercises to assist beginners at reading and writing Python code. [WIP]"
link = "https://github.com/THEGOLDENPRO/snakelings"
image = "https://raw.githubusercontent.com/THEGOLDENPRO/snakelings/main/assets/preview.png"

[[config.projects]]
name = "😺 http-cat-cli"
link = "https://github.com/THEGOLDENPRO/http-cat-cli"
image = "https://raw.githubusercontent.com/THEGOLDENPRO/http-cat-cli/main/assets/http_cat_showcase.png"

[[config.projects]]
name = "Anmoku 安黙"
description = "A peaceful and fully typed MyAnimeList / Jikan Python API wrapper with caching and proper rate limiting."
link = "https://github.com/THEGOLDENPRO/anmoku"